# Classifying Penguins with Keras

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [2]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins = penguins.dropna()
penguins.head()

Requirement already satisfied: palmerpenguins in ./.venv/lib/python3.11/site-packages (0.1.6)
Requirement already satisfied: pandas in ./.venv/lib/python3.11/site-packages (from palmerpenguins) (3.0.3)
Requirement already satisfied: numpy in ./.venv/lib/python3.11/site-packages (from palmerpenguins) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007

In [3]:
#SHUFFLE THE DATA
penguins = penguins.sample(frac=1).reset_index(drop=True)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Biscoe,40.1,18.9,188.0,4300.0,male,2008
1,Chinstrap,Dream,54.2,20.8,201.0,4300.0,male,2008
2,Gentoo,Biscoe,42.7,13.7,208.0,3950.0,female,2008
3,Chinstrap,Dream,49.2,18.2,195.0,4400.0,male,2007
4,Adelie,Biscoe,41.4,18.6,191.0,3700.0,male,2008

In [4]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,4300.0,40.1,18.9,188.0,False,True
1,4300.0,54.2,20.8,201.0,False,True
2,3950.0,42.7,13.7,208.0,True,False
3,4400.0,49.2,18.2,195.0,False,True
4,3700.0,41.4,18.6,191.0,False,True
...,...,...,...,...,...,...
328,3875.0,41.4,18.5,202.0,False,True
329,4100.0,51.0,18.8,203.0,False,True
330,4650.0,45.5,13.7,214.0,True,False
331,3000.0,37.0,16.9,185.0,True,False
332,4250.0,39.2,18.6,190.0,False,True

In [5]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.444444,0.290909,0.690476,0.271186,0.0,1.0
1,0.444444,0.803636,0.916667,0.491525,0.0,1.0
2,0.347222,0.385455,0.071429,0.610169,1.0,0.0
3,0.472222,0.621818,0.607143,0.389831,0.0,1.0
4,0.277778,0.338182,0.654762,0.322034,0.0,1.0
...,...,...,...,...,...,...
328,0.326389,0.338182,0.642857,0.508475,0.0,1.0
329,0.388889,0.687273,0.678571,0.525424,0.0,1.0
330,0.541667,0.487273,0.071429,0.711864,1.0,0.0
331,0.083333,0.178182,0.452381,0.220339,1.0,0.0
332,0.430556,0.258182,0.654762,0.305085,0.0,1.0

In [6]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Gentoo
3      Chinstrap
4         Adelie
         ...
328       Adelie
329    Chinstrap
330       Gentoo
331       Adelie
332       Adelie
Name: species, Length: 333, dtype: str

array([0, 1, 2, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 1, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 2,
       0, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1, 2, 1, 2, 0, 1, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2,
       1, 1, 2, 0, 2, 1, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2,
       1, 2, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0,
       1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 1, 2, 0, 1, 1, 2, 0, 0, 2, 1, 1, 0,
       0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0,
       1, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 1, 0, 2, 2,
       1, 2, 2, 2, 0, 1, 0, 1, 2, 2, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       2, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 0, 2, 0, 1, 2,
       0, 0, 2, 1, 1, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1,
       2, 0, 0], dtype=int8)

In [7]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [8]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [10]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

/Users/mkenne16/Documents/Advanced Machine Learning/week 7/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.4381 - loss: 1.2141 - val_accuracy: 0.4412 - val_loss: 1.2237
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5084 - loss: 1.1728 - val_accuracy: 0.3529 - val_loss: 1.1972
Epoch 3/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4531 - loss: 1.1857

/Users/mkenne16/Documents/Advanced Machine Learning/week 7/.venv/lib/python3.11/site-packages/keras/src/backend/tensorflow/nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4515 - loss: 1.1511 - val_accuracy: 0.3529 - val_loss: 1.1777
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 1.1345 - val_accuracy: 0.3529 - val_loss: 1.1622
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 1.1207 - val_accuracy: 0.3529 - val_loss: 1.1482
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 1.1088 - val_accuracy: 0.3529 - val_loss: 1.1353
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4482 - loss: 1.0983 - val_accuracy: 0.3529 - val_loss: 1.1246
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4482 - loss: 1.0888 - val_accuracy: 0.3529 - val_loss: 1.1145
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4482 - loss: 1.0807 - val_accuracy: 0.3529 - val_loss: 1.1055
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4482 - loss: 1.0726 - val_accuracy: 0.3529 - val_loss: 1.0960
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4482 - loss: 1.0651 - val_accuracy: 0.3529 - val_loss: 1.0877
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4482 - loss: 1.0579 - val_accuracy: 0.3529 - val_loss: 1.0808
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 1.0513 - val_accuracy: 0.3529 - val_loss: 1.0734
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 1.0451 - val_accuracy: 0.3529 - val_loss: 1.0665
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 1.0391 - val_accuracy: 0.3529 - val_loss: 1.0610
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 1.0332 - val_accuracy: 0.3529 - val_loss: 1.0547
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 1.0278 - val_accuracy: 0.3529 - val_loss: 1.0488
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4482 - loss: 1.0224 - val_accuracy: 0.3529 - val_loss: 1.0430
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4482 - loss: 1.0173 - val_accuracy: 0.3529 - val_loss: 1.0374
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4482 - loss: 1.0121 - val_accuracy: 0.3529 - val_loss: 1.0320
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 1.0071 - val_accuracy: 0.3529 - val_loss: 1.0263
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 1.0023 - val_accuracy: 0.3529 - val_loss: 1.0207
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9974 - val_accuracy: 0.3529 - val_loss: 1.0155
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4482 - loss: 0.9926 - val_accuracy: 0.3529 - val_loss: 1.0100
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9883 - val_accuracy: 0.3529 - val_loss: 1.0053
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9835 - val_accuracy: 0.3529 - val_loss: 1.0011
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9795 - val_accuracy: 0.3529 - val_loss: 0.9958
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9754 - val_accuracy: 0.3529 - val_loss: 0.9909
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4482 - loss: 0.9711 - val_accuracy: 0.3529 - val_loss: 0.9857
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4482 - loss: 0.9666 - val_accuracy: 0.3529 - val_loss: 0.9806
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9627 - val_accuracy: 0.3529 - val_loss: 0.9758
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9586 - val_accuracy: 0.3529 - val_loss: 0.9708
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9538 - val_accuracy: 0.3529 - val_loss: 0.9664
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9500 - val_accuracy: 0.3529 - val_loss: 0.9616
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9452 - val_accuracy: 0.3529 - val_loss: 0.9570
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9409 - val_accuracy: 0.3529 - val_loss: 0.9517
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9362 - val_accuracy: 0.3529 - val_loss: 0.9461
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9310 - val_accuracy: 0.3529 - val_loss: 0.9396
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9266 - val_accuracy: 0.3529 - val_loss: 0.9340
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9214 - val_accuracy: 0.3529 - val_loss: 0.9289
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9160 - val_accuracy: 0.3529 - val_loss: 0.9236
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9114 - val_accuracy: 0.3529 - val_loss: 0.9176
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9056 - val_accuracy: 0.3529 - val_loss: 0.9113
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.9003 - val_accuracy: 0.3529 - val_loss: 0.9053
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.8950 - val_accuracy: 0.3529 - val_loss: 0.8984
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4515 - loss: 0.8893 - val_accuracy: 0.3529 - val_loss: 0.8918
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4482 - loss: 0.8835 - val_accuracy: 0.3529 - val_loss: 0.8862
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4515 - loss: 0.8778 - val_accuracy: 0.3529 - val_loss: 0.8798
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4548 - loss: 0.8722 - val_accuracy: 0.3529 - val_loss: 0.8730
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4515 - loss: 0.8666 - val_accuracy: 0.3529 - val_loss: 0.8664
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4548 - loss: 0.8607 - val_accuracy: 0.3529 - val_loss: 0.8610
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4582 - loss: 0.8551 - val_accuracy: 0.3529 - val_loss: 0.8554
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4582 - loss: 0.8493 - val_accuracy: 0.3529 - val_loss: 0.8483
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4615 - loss: 0.8437 - val_accuracy: 0.3824 - val_loss: 0.8412
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4649 - loss: 0.8375 - val_accuracy: 0.4118 - val_loss: 0.8353
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4682 - loss: 0.8319 - val_accuracy: 0.4118 - val_loss: 0.8289
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4849 - loss: 0.8259 - val_accuracy: 0.4118 - val_loss: 0.8236
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4883 - loss: 0.8196 - val_accuracy: 0.4118 - val_loss: 0.8170
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4950 - loss: 0.8145 - val_accuracy: 0.4118 - val_loss: 0.8111
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5017 - loss: 0.8076 - val_accuracy: 0.4412 - val_loss: 0.8044
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5151 - loss: 0.8018 - val_accuracy: 0.5294 - val_loss: 0.7976
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5518 - loss: 0.7959 - val_accuracy: 0.5294 - val_loss: 0.7929
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5385 - loss: 0.7895 - val_accuracy: 0.5294 - val_loss: 0.7870
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5552 - loss: 0.7839 - val_accuracy: 0.5294 - val_loss: 0.7819
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5585 - loss: 0.7780 - val_accuracy: 0.5294 - val_loss: 0.7760
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5753 - loss: 0.7720 - val_accuracy: 0.5588 - val_loss: 0.7700
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5753 - loss: 0.7660 - val_accuracy: 0.5588 - val_loss: 0.7649
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6020 - loss: 0.7600 - val_accuracy: 0.5294 - val_loss: 0.7596
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6154 - loss: 0.7540 - val_accuracy: 0.5588 - val_loss: 0.7524
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6020 - loss: 0.7483 - val_accuracy: 0.6176 - val_loss: 0.7454
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6355 - loss: 0.7419 - val_accuracy: 0.6176 - val_loss: 0.7391
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6321 - loss: 0.7356 - val_accuracy: 0.7059 - val_loss: 0.7328
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6689 - loss: 0.7304 - val_accuracy: 0.7059 - val_loss: 0.7281
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6722 - loss: 0.7240 - val_accuracy: 0.7647 - val_loss: 0.7207
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6856 - loss: 0.7180 - val_accuracy: 0.7353 - val_loss: 0.7151
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7090 - loss: 0.7122 - val_accuracy: 0.7647 - val_loss: 0.7071
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7525 - loss: 0.7065 - val_accuracy: 0.7647 - val_loss: 0.7000
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7559 - loss: 0.7010 - val_accuracy: 0.7647 - val_loss: 0.6944
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7860 - loss: 0.6951 - val_accuracy: 0.7941 - val_loss: 0.6876
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7893 - loss: 0.6895 - val_accuracy: 0.8235 - val_loss: 0.6812
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8127 - loss: 0.6846 - val_accuracy: 0.7941 - val_loss: 0.6770
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8161 - loss: 0.6787 - val_accuracy: 0.8529 - val_loss: 0.6707
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8127 - loss: 0.6737 - val_accuracy: 0.8824 - val_loss: 0.6643
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8294 - loss: 0.6687 - val_accuracy: 0.8235 - val_loss: 0.6603
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8428 - loss: 0.6614 - val_accuracy: 0.8529 - val_loss: 0.6530
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8462 - loss: 0.6550 - val_accuracy: 0.8529 - val_loss: 0.6474
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8562 - loss: 0.6483 - val_accuracy: 0.8235 - val_loss: 0.6424
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8629 - loss: 0.6424 - val_accuracy: 0.8235 - val_loss: 0.6380
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8629 - loss: 0.6354 - val_accuracy: 0.8824 - val_loss: 0.6309
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8696 - loss: 0.6295 - val_accuracy: 0.8824 - val_loss: 0.6249
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8863 - loss: 0.6237 - val_accuracy: 0.8824 - val_loss: 0.6202
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8896 - loss: 0.6175 - val_accuracy: 0.8824 - val_loss: 0.6150
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8829 - loss: 0.6109 - val_accuracy: 0.8824 - val_loss: 0.6078
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8896 - loss: 0.6055 - val_accuracy: 0.9118 - val_loss: 0.6009
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8930 - loss: 0.5992 - val_accuracy: 0.8824 - val_loss: 0.5971
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8896 - loss: 0.5940 - val_accuracy: 0.8824 - val_loss: 0.5916
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8997 - loss: 0.5888 - val_accuracy: 0.9118 - val_loss: 0.5873
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8963 - loss: 0.5828 - val_accuracy: 0.9118 - val_loss: 0.5815
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9197 - loss: 0.5782 - val_accuracy: 0.9118 - val_loss: 0.5775
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9197 - loss: 0.5720 - val_accuracy: 0.9118 - val_loss: 0.5717
11/11 - 0s - 3ms/step - accuracy: 0.9189 - loss: 0.5684

In [11]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.8997 - loss: 0.5641 - val_accuracy: 0.9412 - val_loss: 0.5584
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9164 - loss: 0.5535 - val_accuracy: 0.9412 - val_loss: 0.5502
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9264 - loss: 0.5456 - val_accuracy: 0.9412 - val_loss: 0.5433
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9298 - loss: 0.5394 - val_accuracy: 0.9412 - val_loss: 0.5354
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9298 - loss: 0.5331 - val_accuracy: 0.9412 - val_loss: 0.5292
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9298 - loss: 0.5273 - val_accuracy: 0.9412 - val_loss: 0.5233
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9398 - loss: 0.5210 - val_accuracy: 0.9412 - val_loss: 0.5190
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9398 - loss: 0.5157 - val_accuracy: 0.9412 - val_loss: 0.5154
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9264 - loss: 0.5100 - val_accuracy: 0.9412 - val_loss: 0.5054
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.5044 - val_accuracy: 0.9412 - val_loss: 0.5003
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.4990 - val_accuracy: 0.9412 - val_loss: 0.4982
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9398 - loss: 0.4937 - val_accuracy: 0.9412 - val_loss: 0.4932
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9365 - loss: 0.4887 - val_accuracy: 0.9412 - val_loss: 0.4874
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9331 - loss: 0.4829 - val_accuracy: 0.9412 - val_loss: 0.4786
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9498 - loss: 0.4782 - val_accuracy: 0.9412 - val_loss: 0.4756
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9532 - loss: 0.4728 - val_accuracy: 0.9412 - val_loss: 0.4739
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.4669 - val_accuracy: 0.9412 - val_loss: 0.4646
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9599 - loss: 0.4626 - val_accuracy: 0.9412 - val_loss: 0.4608
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.4564 - val_accuracy: 0.9412 - val_loss: 0.4569
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.4515 - val_accuracy: 0.9412 - val_loss: 0.4543
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.4460 - val_accuracy: 0.9412 - val_loss: 0.4503
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9498 - loss: 0.4412 - val_accuracy: 0.9412 - val_loss: 0.4407
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9565 - loss: 0.4355 - val_accuracy: 0.9412 - val_loss: 0.4333
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9632 - loss: 0.4300 - val_accuracy: 0.9412 - val_loss: 0.4293
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9599 - loss: 0.4250 - val_accuracy: 0.9412 - val_loss: 0.4225
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9632 - loss: 0.4197 - val_accuracy: 0.9412 - val_loss: 0.4169
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9666 - loss: 0.4142 - val_accuracy: 0.9412 - val_loss: 0.4147
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9599 - loss: 0.4090 - val_accuracy: 0.9706 - val_loss: 0.4062
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9699 - loss: 0.4031 - val_accuracy: 0.9706 - val_loss: 0.3999
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9632 - loss: 0.3982 - val_accuracy: 0.9706 - val_loss: 0.3936
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9732 - loss: 0.3927 - val_accuracy: 0.9706 - val_loss: 0.3919
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9666 - loss: 0.3881 - val_accuracy: 0.9706 - val_loss: 0.3839
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9732 - loss: 0.3827 - val_accuracy: 0.9706 - val_loss: 0.3812
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9699 - loss: 0.3778 - val_accuracy: 0.9706 - val_loss: 0.3770
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9699 - loss: 0.3730 - val_accuracy: 0.9706 - val_loss: 0.3687
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9732 - loss: 0.3684 - val_accuracy: 0.9706 - val_loss: 0.3684
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9766 - loss: 0.3633 - val_accuracy: 0.9706 - val_loss: 0.3624
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9799 - loss: 0.3583 - val_accuracy: 0.9706 - val_loss: 0.3552
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9766 - loss: 0.3546 - val_accuracy: 0.9706 - val_loss: 0.3542
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9799 - loss: 0.3498 - val_accuracy: 0.9706 - val_loss: 0.3466
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9766 - loss: 0.3460 - val_accuracy: 0.9706 - val_loss: 0.3443
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.3411 - val_accuracy: 0.9706 - val_loss: 0.3452
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.3372 - val_accuracy: 0.9706 - val_loss: 0.3390
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.3328 - val_accuracy: 0.9706 - val_loss: 0.3316
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.3293 - val_accuracy: 0.9706 - val_loss: 0.3303
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.3258 - val_accuracy: 0.9706 - val_loss: 0.3268
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.3212 - val_accuracy: 0.9706 - val_loss: 0.3217
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9766 - loss: 0.3177 - val_accuracy: 0.9706 - val_loss: 0.3215
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.3137 - val_accuracy: 0.9706 - val_loss: 0.3157
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9799 - loss: 0.3104 - val_accuracy: 0.9706 - val_loss: 0.3153
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.3063 - val_accuracy: 0.9706 - val_loss: 0.3073
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9799 - loss: 0.3038 - val_accuracy: 0.9706 - val_loss: 0.3031
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9833 - loss: 0.2997 - val_accuracy: 0.9706 - val_loss: 0.2999
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2958 - val_accuracy: 0.9706 - val_loss: 0.2985
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2928 - val_accuracy: 0.9706 - val_loss: 0.2916
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2893 - val_accuracy: 0.9706 - val_loss: 0.2887
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9833 - loss: 0.2859 - val_accuracy: 0.9706 - val_loss: 0.2848
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2829 - val_accuracy: 0.9706 - val_loss: 0.2796
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9799 - loss: 0.2795 - val_accuracy: 0.9706 - val_loss: 0.2773
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9799 - loss: 0.2755 - val_accuracy: 0.9706 - val_loss: 0.2743
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2723 - val_accuracy: 0.9706 - val_loss: 0.2744
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2693 - val_accuracy: 0.9706 - val_loss: 0.2673
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2673 - val_accuracy: 0.9706 - val_loss: 0.2668
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2628 - val_accuracy: 0.9706 - val_loss: 0.2611
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2607 - val_accuracy: 0.9706 - val_loss: 0.2627
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2571 - val_accuracy: 0.9706 - val_loss: 0.2589
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2541 - val_accuracy: 0.9706 - val_loss: 0.2586
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2510 - val_accuracy: 0.9706 - val_loss: 0.2567
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2486 - val_accuracy: 0.9706 - val_loss: 0.2482
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2454 - val_accuracy: 0.9706 - val_loss: 0.2432
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2423 - val_accuracy: 0.9706 - val_loss: 0.2450
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2406 - val_accuracy: 0.9706 - val_loss: 0.2441
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2366 - val_accuracy: 0.9706 - val_loss: 0.2441
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2356 - val_accuracy: 0.9706 - val_loss: 0.2407
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2319 - val_accuracy: 0.9706 - val_loss: 0.2364
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9866 - loss: 0.2295 - val_accuracy: 0.9706 - val_loss: 0.2300
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2268 - val_accuracy: 0.9706 - val_loss: 0.2343
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2247 - val_accuracy: 0.9706 - val_loss: 0.2300
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2219 - val_accuracy: 0.9706 - val_loss: 0.2287
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2196 - val_accuracy: 0.9706 - val_loss: 0.2260
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2172 - val_accuracy: 0.9706 - val_loss: 0.2238
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2146 - val_accuracy: 0.9706 - val_loss: 0.2185
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2116 - val_accuracy: 0.9706 - val_loss: 0.2159
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9866 - loss: 0.2092 - val_accuracy: 0.9706 - val_loss: 0.2106
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.2063 - val_accuracy: 0.9706 - val_loss: 0.2144
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.2058 - val_accuracy: 0.9706 - val_loss: 0.2081
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9833 - loss: 0.2029 - val_accuracy: 0.9706 - val_loss: 0.2088
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1997 - val_accuracy: 0.9706 - val_loss: 0.2050
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1979 - val_accuracy: 0.9706 - val_loss: 0.2044
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9833 - loss: 0.1956 - val_accuracy: 0.9706 - val_loss: 0.2036
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1931 - val_accuracy: 0.9706 - val_loss: 0.1962
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1909 - val_accuracy: 0.9706 - val_loss: 0.1980
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1888 - val_accuracy: 0.9706 - val_loss: 0.1950
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1873 - val_accuracy: 0.9706 - val_loss: 0.1972
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.1850 - val_accuracy: 0.9706 - val_loss: 0.1915
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9900 - loss: 0.1828 - val_accuracy: 0.9706 - val_loss: 0.1922
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9866 - loss: 0.1817 - val_accuracy: 0.9706 - val_loss: 0.1920
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9866 - loss: 0.1789 - val_accuracy: 0.9706 - val_loss: 0.1826
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9900 - loss: 0.1770 - val_accuracy: 0.9706 - val_loss: 0.1824
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9900 - loss: 0.1748 - val_accuracy: 0.9706 - val_loss: 0.1802
11/11 - 0s - 4ms/step - accuracy: 0.9850 - loss: 0.1739

In [12]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

array([[9.95033860e-01, 1.01200864e-03, 3.95405106e-03],
       [5.01229893e-03, 9.94987369e-01, 3.95297604e-07],
       [1.68231815e-01, 1.03896260e-01, 7.27871895e-01],
       [1.99769616e-01, 7.98085690e-01, 2.14463286e-03],
       [9.82876301e-01, 1.19698877e-02, 5.15391491e-03],
       [1.65044099e-01, 1.06453694e-01, 7.28502154e-01],
       [9.97649550e-01, 4.50266525e-04, 1.90011109e-03],
       [9.91859794e-01, 1.90873072e-03, 6.23157015e-03],
       [8.08156252e-01, 1.90789416e-01, 1.05439976e-03],
       [1.27293304e-01, 8.72645080e-01, 6.15698154e-05],
       [9.95612919e-01, 4.78455506e-04, 3.90868960e-03],
       [1.43781621e-02, 9.85620201e-01, 1.67481733e-06],
       [1.05582811e-02, 9.89437878e-01, 3.77241918e-06],
       [1.69009045e-01, 1.03284925e-01, 7.27706075e-01],
       [9.81998622e-01, 1.49540389e-02, 3.04741808e-03],
       [9.96967375e-01, 9.89786349e-04, 2.04291963e-03],
       [1.11651300e-02, 9.88832951e-01, 1.83644102e-06],
       [2.93145906e-02, 9.70629573e-01, 5.58074425e-05],
       [2.40574013e-02, 9.75940585e-01, 1.96159863e-06],
       [1.48762107e-01, 1.20902784e-01, 7.30335116e-01],
       [9.57039595e-01, 3.31498347e-02, 9.81055293e-03],
       [8.44618738e-01, 1.54621512e-01, 7.59781396e-04],
       [1.55287281e-01, 1.14816226e-01, 7.29896426e-01],
       [9.59494054e-01, 3.31134684e-02, 7.39257783e-03],
       [9.96531367e-01, 2.50469055e-03, 9.63851053e-04],
       [9.70604300e-01, 1.74658950e-02, 1.19298212e-02],
       [9.14965808e-01, 8.38951916e-02, 1.13893929e-03],
       [9.94193137e-01, 4.03856300e-03, 1.76829891e-03],
       [9.57789302e-01, 4.02408578e-02, 1.96976471e-03],
       [1.61481142e-01, 1.09411068e-01, 7.29107738e-01],
       [1.53172046e-01, 1.16743408e-01, 7.30084479e-01],
       [9.73632634e-01, 2.22235881e-02, 4.14375914e-03],
       [1.45786498e-02, 9.85400438e-01, 2.09709815e-05],
       [2.00242419e-02, 9.79968488e-01, 7.26676126e-06],
       [9.96626377e-01, 1.93431682e-03, 1.43940398e-03],
       [1.58734635e-01, 1.11765265e-01, 7.29500115e-01],
       [1.59799650e-01, 1.10844471e-01, 7.29355872e-01],
       [9.98235583e-01, 4.34743299e-04, 1.32970558e-03],
       [8.79951566e-02, 9.11322832e-01, 6.82032900e-04],
       [9.50004578e-01, 9.38952714e-03, 4.06059064e-02],
       [5.94034381e-02, 9.40378606e-01, 2.17904118e-04],
       [9.97833490e-01, 1.74804169e-04, 1.99159444e-03],
       [1.62544295e-01, 1.08517393e-01, 7.28938282e-01],
       [1.51345119e-01, 1.18442848e-01, 7.30211914e-01],
       [9.01770592e-01, 9.65738669e-02, 1.65545172e-03],
       [6.09344207e-02, 9.38961506e-01, 1.04132974e-04],
       [9.39059973e-01, 5.91154471e-02, 1.82453776e-03],
       [9.84351933e-01, 6.81152986e-03, 8.83645657e-03],
       [9.77841973e-01, 1.59963127e-02, 6.16178941e-03],
       [1.72945499e-01, 1.00259788e-01, 7.26794660e-01],
       [1.55338436e-01, 1.14770167e-01, 7.29891360e-01],
       [2.66627014e-01, 7.32795477e-01, 5.77533792e-04],
       [8.99583042e-01, 9.94652882e-02, 9.51788214e-04],
       [1.58773825e-01, 1.11731209e-01, 7.29494989e-01],
       [9.98401284e-01, 1.70307205e-04, 1.42833905e-03],
       [1.58972681e-01, 1.11558579e-01, 7.29468763e-01],
       [1.20381236e-01, 8.78077447e-01, 1.54128030e-03],
       [1.65692434e-01, 1.05926916e-01, 7.28380620e-01],
       [7.51978345e-03, 9.92475152e-01, 5.09729716e-06],
       [1.59594730e-01, 1.11020893e-01, 7.29384482e-01],
       [6.85935915e-01, 3.13825339e-01, 2.38801498e-04],
       [2.26387262e-01, 7.72695363e-01, 9.17313562e-04],
       [9.71059203e-01, 1.29799210e-02, 1.59609243e-02],
       [1.58253819e-01, 1.12184256e-01, 7.29561925e-01],
       [1.55126676e-01, 1.14961065e-01, 7.29912221e-01],
       [1.59163326e-01, 1.11393422e-01, 7.29443312e-01],
       [1.62956059e-01, 1.08173884e-01, 7.28870094e-01],
       [1.74238041e-01, 9.92916673e-02, 7.26470292e-01],
       [1.61561236e-01, 1.09343454e-01, 7.29095399e-01],
       [9.59260166e-01, 3.54060978e-02, 5.33377845e-03],
       [9.92557049e-01, 3.91824637e-03, 3.52464477e-03],
       [1.55535176e-01, 1.14593156e-01, 7.29871571e-01],
       [7.09870132e-03, 9.92900491e-01, 7.98881445e-07],
       [4.70445275e-01, 5.29160738e-01, 3.94015340e-04],
       [1.62462994e-01, 1.08585395e-01, 7.28951573e-01],
       [1.56109527e-01, 1.14078566e-01, 7.29811847e-01],
       [1.99519798e-01, 8.00171554e-01, 3.08632909e-04],
       [9.75207508e-01, 1.15330853e-02, 1.32594183e-02],
       [9.97163534e-01, 4.74226603e-04, 2.36231694e-03],
       [9.22779143e-01, 1.11896126e-02, 6.60311952e-02],
       [1.55175760e-01, 1.14916787e-01, 7.29907393e-01],
       [9.79427934e-01, 4.09445725e-04, 2.01625880e-02],
       [1.42318299e-02, 9.85766828e-01, 1.30153342e-06],
       [9.98139024e-01, 6.02036889e-04, 1.25890947e-03],
       [1.75786331e-01, 9.81478840e-02, 7.26065695e-01],
       [9.66594100e-01, 2.72310358e-02, 6.17484935e-03],
       [1.55579627e-01, 1.14553265e-01, 7.29867160e-01],
       [1.66373983e-01, 1.05376855e-01, 7.28249252e-01],
       [9.59366918e-01, 1.79065336e-02, 2.27264445e-02],
       [9.67118204e-01, 2.32256930e-02, 9.65622347e-03],
       [1.57651588e-01, 1.12712033e-01, 7.29636431e-01],
       [9.81044948e-01, 7.39529729e-03, 1.15596056e-02],
       [1.57633796e-01, 1.12727679e-01, 7.29638517e-01],
       [8.84140193e-01, 1.14086606e-01, 1.77318766e-03],
       [8.27565014e-01, 1.65310442e-01, 7.12463260e-03],
       [1.32701145e-02, 9.86718476e-01, 1.13802553e-05],
       [9.66410577e-01, 2.18305867e-02, 1.17588593e-02],
       [1.70258790e-01, 1.02311783e-01, 7.27429509e-01],
       [9.50618923e-01, 4.77407724e-02, 1.64038443e-03],
       [1.55494586e-01, 1.14629693e-01, 7.29875803e-01],
       [1.52665064e-01, 1.17211707e-01, 7.30123162e-01],
       [1.57976523e-01, 1.12426862e-01, 7.29596615e-01],
       [9.59487617e-01, 2.92152595e-02, 1.12970602e-02],
       [8.74982357e-01, 1.24804899e-01, 2.12785104e-04],
       [9.93925691e-01, 3.21970345e-03, 2.85459706e-03],
       [9.62264359e-01, 3.01637482e-02, 7.57183461e-03],
       [8.56399119e-01, 1.43157080e-01, 4.43835102e-04],
       [1.63278311e-01, 1.07906014e-01, 7.28815675e-01],
       [1.27601232e-02, 9.87194598e-01, 4.53198118e-05],
       [1.64970592e-01, 1.06513642e-01, 7.28515744e-01],
       [9.54756215e-02, 9.04209733e-01, 3.14665231e-04],
       [3.38662714e-02, 9.66101825e-01, 3.18639431e-05],
       [1.58952728e-01, 1.11575879e-01, 7.29471385e-01],
       [9.94347811e-01, 5.01777628e-04, 5.15047275e-03],
       [1.55907720e-01, 1.14259034e-01, 7.29833186e-01],
       [1.99062333e-01, 8.00689876e-01, 2.47809599e-04],
       [9.88748014e-01, 5.72027592e-03, 5.53175900e-03],
       [1.66828021e-01, 1.05012476e-01, 7.28159547e-01],
       [8.12977493e-01, 1.86373100e-01, 6.49392139e-04],
       [9.92934287e-01, 7.20886048e-04, 6.34486554e-03],
       [7.97438681e-01, 2.00656906e-01, 1.90445676e-03],
       [8.30953181e-01, 1.65389687e-01, 3.65715823e-03],
       [9.66542006e-01, 1.07666170e-02, 2.26914585e-02],
       [1.55755013e-01, 1.14395857e-01, 7.29849160e-01],
       [1.60388589e-01, 1.10339619e-01, 7.29271770e-01],
       [9.67478871e-01, 2.52561737e-02, 7.26491632e-03],
       [1.61252156e-01, 1.09604850e-01, 7.29143023e-01],
       [1.63634121e-01, 1.07611284e-01, 7.28754580e-01],
       [6.10276282e-01, 3.89657021e-01, 6.66337728e-05],
       [1.94131639e-02, 9.80583251e-01, 3.65703022e-06],
       [1.61435768e-01, 1.09449431e-01, 7.29114771e-01],
       [1.57269478e-01, 1.13048628e-01, 7.29681909e-01],
       [5.94008528e-02, 9.40575302e-01, 2.38323228e-05],
       [1.67961866e-01, 1.04109660e-01, 7.27928400e-01],
       [7.69686773e-02, 9.23026741e-01, 4.58099521e-06],
       [9.66243863e-01, 2.96572931e-02, 4.09879489e-03],
       [9.48078632e-01, 5.03526740e-02, 1.56855665e-03],
       [8.30480933e-01, 1.68699786e-01, 8.19334004e-04],
       [9.72630620e-01, 1.48501918e-02, 1.25190709e-02],
       [4.98932421e-01, 5.01016200e-01, 5.14286003e-05],
       [1.58563972e-01, 1.11913733e-01, 7.29522228e-01],
       [8.33167434e-01, 1.66233927e-01, 5.98658342e-04],
       [1.64552778e-01, 1.06855221e-01, 7.28592038e-01],
       [9.81398106e-01, 1.24144843e-02, 6.18744548e-03],
       [1.64155334e-01, 1.07181445e-01, 7.28663146e-01],
       [1.91083048e-02, 9.80874300e-01, 1.73439657e-05],
       [9.26054299e-01, 7.17542619e-02, 2.19146651e-03],
       [1.50447354e-01, 1.19290151e-01, 7.30262458e-01],
       [8.61497130e-03, 9.91378605e-01, 6.51673736e-06],
       [9.36274111e-01, 6.20230362e-02, 1.70288142e-03],
       [9.62823868e-01, 1.19104413e-02, 2.52656136e-02],
       [2.24803135e-01, 7.74369001e-01, 8.27847514e-04],
       [1.62893340e-01, 1.08226091e-01, 7.28880465e-01],
       [9.74397182e-01, 1.74510702e-02, 8.15167837e-03],
       [9.74105835e-01, 1.84533950e-02, 7.44074909e-03],
       [1.65177599e-01, 1.06344946e-01, 7.28477418e-01],
       [1.49062067e-01, 1.20613597e-01, 7.30324268e-01],
       [1.70400470e-01, 1.04550220e-01, 7.25049376e-01],
       [1.66460127e-01, 1.05307542e-01, 7.28232205e-01],
       [8.52837861e-01, 1.46230146e-01, 9.32014431e-04],
       [9.95057285e-01, 4.40864533e-04, 4.50171623e-03],
       [9.72403586e-01, 1.49053177e-02, 1.26911355e-02],
       [9.97333348e-01, 1.88437628e-03, 7.82193849e-04],
       [1.68161839e-01, 1.03951521e-01, 7.27886617e-01],
       [1.54584378e-01, 1.15451910e-01, 7.29963720e-01],
       [1.67256713e-01, 1.04669929e-01, 7.28073359e-01],
       [8.15233402e-03, 9.91846204e-01, 1.42533406e-06],
       [9.66237962e-01, 2.89314743e-02, 4.83052852e-03],
       [9.79280829e-01, 8.92555621e-03, 1.17936507e-02],
       [9.71662700e-01, 4.19673370e-03, 2.41406001e-02],
       [9.60183322e-01, 3.60619426e-02, 3.75474244e-03],
       [1.61116034e-01, 1.09720230e-01, 7.29163706e-01],
       [1.59318402e-01, 1.11259282e-01, 7.29422271e-01],
       [1.63812935e-01, 1.07463568e-01, 7.28723466e-01],
       [9.75432217e-01, 6.89255819e-03, 1.76752303e-02],
       [9.91739094e-01, 8.52141704e-04, 7.40874093e-03],
       [1.65066198e-02, 9.83475089e-01, 1.83227676e-05],
       [9.46510077e-01, 4.70544435e-02, 6.43543899e-03],
       [1.96788758e-01, 1.17304750e-01, 6.85906529e-01],
       [8.97000730e-01, 1.00962348e-01, 2.03695009e-03],
       [1.62688762e-01, 1.08396731e-01, 7.28914559e-01],
       [1.62160352e-01, 1.08839013e-01, 7.29000568e-01],
       [6.45614326e-01, 2.71453530e-01, 8.29321295e-02],
       [9.74275649e-01, 1.34868547e-02, 1.22374846e-02],
       [1.64514303e-01, 1.06886744e-01, 7.28599012e-01],
       [9.89188313e-01, 6.64253661e-04, 1.01473527e-02],
       [4.97092977e-02, 9.50272441e-01, 1.82308431e-05],
       [1.97074026e-01, 8.40079188e-02, 7.18918025e-01],
       [9.49219525e-01, 4.90071215e-02, 1.77333062e-03],
       [6.34148121e-01, 3.64608467e-01, 1.24341936e-03],
       [7.49728605e-02, 9.24860299e-01, 1.66903570e-04],
       [1.57377720e-01, 1.12953134e-01, 7.29669154e-01],
       [9.53812182e-01, 4.10264619e-02, 5.16148657e-03],
       [9.79354560e-01, 1.72244292e-03, 1.89231634e-02],
       [1.64462477e-01, 1.06929220e-01, 7.28608310e-01],
       [2.90960148e-02, 9.70865965e-01, 3.80603196e-05],
       [7.37804770e-02, 9.26170707e-01, 4.87827274e-05],
       [9.01819825e-01, 9.69319493e-02, 1.24823523e-03],
       [8.99924815e-01, 9.54572856e-02, 4.61778929e-03],
       [8.60683322e-01, 1.39056325e-01, 2.60358560e-04],
       [9.66799200e-01, 8.40952713e-03, 2.47912332e-02],
       [9.82553840e-01, 6.04810147e-03, 1.13981329e-02],
       [1.49078831e-01, 1.20597482e-01, 7.30323732e-01],
       [1.23782419e-01, 8.76168311e-01, 4.92640684e-05],
       [3.12136370e-04, 9.99687910e-01, 2.86010238e-09],
       [1.21024199e-01, 8.78880918e-01, 9.49707901e-05],
       [9.34979022e-01, 6.29447103e-02, 2.07629986e-03],
       [8.81802797e-01, 1.16027907e-01, 2.16930476e-03],
       [9.29007947e-01, 1.41696101e-02, 5.68225272e-02],
       [8.97361457e-01, 1.01388931e-01, 1.24959520e-03],
       [1.64277017e-01, 1.07081428e-01, 7.28641510e-01],
       [1.53130069e-01, 1.16782106e-01, 7.30087876e-01],
       [1.60598010e-01, 1.10160828e-01, 7.29241133e-01],
       [1.61818668e-01, 1.09126322e-01, 7.29055047e-01],
       [1.65731668e-01, 1.05895117e-01, 7.28373110e-01],
       [9.39884305e-01, 5.68868257e-02, 3.22895334e-03],
       [9.90230262e-01, 7.67492037e-03, 2.09486345e-03],
       [9.82066512e-01, 1.16538117e-02, 6.27965899e-03],
       [8.55626836e-02, 9.14384902e-01, 5.24145944e-05],
       [1.63947031e-01, 1.07352950e-01, 7.28699982e-01],
       [1.62781745e-01, 1.08319134e-01, 7.28899062e-01],
       [2.10991260e-02, 9.78801429e-01, 9.93855938e-05],
       [5.14178686e-02, 9.48524892e-01, 5.72216704e-05],
       [3.11973691e-01, 6.87512815e-01, 5.13490115e-04],
       [1.66603163e-01, 1.05192684e-01, 7.28204072e-01],
       [9.73169386e-01, 1.77123975e-02, 9.11820494e-03],
       [9.75249767e-01, 7.82148633e-03, 1.69288125e-02],
       [9.96500134e-01, 9.68741719e-04, 2.53114058e-03],
       [9.46464181e-01, 1.43909054e-02, 3.91448922e-02],
       [9.60182548e-01, 3.07396781e-02, 9.07780323e-03],
       [1.02421731e-01, 8.97576690e-01, 1.63076470e-06],
       [3.16531897e-01, 3.81149910e-02, 6.45353138e-01],
       [1.61186635e-01, 1.09660380e-01, 7.29153037e-01],
       [1.56045482e-01, 1.14135809e-01, 7.29818702e-01],
       [9.83252823e-01, 6.32439135e-03, 1.04228435e-02],
       [9.97442245e-01, 1.34491187e-03, 1.21277617e-03],
       [8.88069689e-01, 3.69023606e-02, 7.50279650e-02],
       [1.58201396e-01, 1.12230085e-01, 7.29568541e-01],
       [8.23635235e-02, 9.17633355e-01, 3.03125694e-06],
       [9.93224740e-01, 7.87599303e-04, 5.98770380e-03],
       [7.29353547e-01, 2.69995779e-01, 6.50701404e-04],
       [9.98363853e-01, 3.00757947e-05, 1.60599174e-03],
       [1.76841065e-01, 8.22624564e-01, 5.34316525e-04],
       [2.50772629e-02, 9.74877536e-01, 4.52415952e-05],
       [9.73765492e-01, 1.46754719e-02, 1.15591083e-02],
       [1.59863248e-01, 1.10789813e-01, 7.29346931e-01],
       [1.63460940e-01, 1.07754625e-01, 7.28784502e-01],
       [7.18278587e-01, 2.72604764e-01, 9.11666360e-03],
       [9.97841239e-01, 6.88210712e-04, 1.47045217e-03],
       [9.98109937e-01, 3.34717188e-04, 1.55540858e-03],
       [9.40688908e-01, 5.66646680e-02, 2.64641037e-03],
       [8.71661425e-01, 1.20429724e-01, 7.90881459e-03],
       [9.13345337e-01, 8.61926824e-02, 4.61945136e-04],
       [9.68071520e-01, 2.54838672e-02, 6.44458411e-03],
       [1.51591569e-01, 1.18211687e-01, 7.30196714e-01],
       [8.88617456e-01, 1.09917037e-01, 1.46558823e-03],
       [7.15891242e-01, 2.83763558e-01, 3.45205044e-04],
       [1.59923553e-01, 1.10738017e-01, 7.29338408e-01],
       [5.30663226e-03, 9.94691968e-01, 1.40993848e-06],
       [9.87227380e-01, 2.79165152e-03, 9.98097938e-03],
       [1.25357211e-01, 8.74600232e-01, 4.25307298e-05],
       [9.86843705e-01, 1.20929116e-02, 1.06331892e-03],
       [1.63845822e-01, 1.07436426e-01, 7.28717744e-01],
       [1.50988728e-01, 1.18778259e-01, 7.30233014e-01],
       [1.00766994e-01, 8.99096966e-01, 1.36012532e-04],
       [1.57339677e-01, 1.64430872e-01, 6.78229392e-01],
       [1.57533005e-01, 1.12816341e-01, 7.29650617e-01],
       [1.57666281e-01, 1.12699129e-01, 7.29634583e-01],
       [8.58988822e-01, 1.40336111e-01, 6.75165153e-04],
       [5.61428107e-02, 9.43435192e-01, 4.22009762e-04],
       [9.81642067e-01, 2.34163180e-03, 1.60164554e-02],
       [9.18640697e-04, 9.99081254e-01, 1.43580039e-07],
       [1.62235081e-01, 2.00342715e-01, 6.37422204e-01],
       [1.62078306e-01, 1.08907886e-01, 7.29013681e-01],
       [6.37119472e-01, 3.62611979e-01, 2.68586940e-04],
       [7.23963454e-02, 9.27063465e-01, 5.40162437e-04],
       [1.49173617e-01, 1.20506279e-01, 7.30320036e-01],
       [1.54798135e-01, 1.15258098e-01, 7.29943752e-01],
       [1.57313123e-01, 1.13010131e-01, 7.29676843e-01],
       [9.00544643e-01, 9.75741521e-02, 1.88129023e-03],
       [9.10565317e-01, 6.58249855e-02, 2.36098208e-02],
       [9.95221674e-01, 2.88468809e-03, 1.89364585e-03],
       [9.98414397e-01, 1.75914669e-04, 1.40969548e-03],
       [9.42342758e-01, 6.42361492e-03, 5.12336232e-02],
       [9.98448789e-01, 9.18748439e-04, 6.32496434e-04],
       [9.97272789e-01, 3.98143224e-04, 2.32911739e-03],
       [1.61455140e-01, 1.09433055e-01, 7.29111850e-01],
       [1.69378191e-01, 1.02996215e-01, 7.27625549e-01],
       [9.66261148e-01, 2.82560401e-02, 5.48277376e-03],
       [9.50054944e-01, 4.83000092e-02, 1.64508866e-03],
       [1.60427600e-01, 1.10306293e-01, 7.29266107e-01],
       [9.71930146e-01, 2.50042304e-02, 3.06559936e-03],
       [1.63789213e-01, 1.07483119e-01, 7.28727579e-01],
       [1.59393623e-01, 1.11194335e-01, 7.29412079e-01],
       [1.51337087e-01, 1.18450418e-01, 7.30212450e-01],
       [1.01037137e-01, 8.98931146e-01, 3.16812802e-05],
       [1.56079575e-01, 1.14105336e-01, 7.29815125e-01],
       [1.58943564e-01, 8.40991676e-01, 6.48024870e-05],
       [1.68064117e-01, 1.04028776e-01, 7.27907121e-01],
       [1.69406325e-01, 1.02974266e-01, 7.27619469e-01],
       [1.53743744e-01, 1.16218291e-01, 7.30037928e-01],
       [5.65473974e-01, 4.34148580e-01, 3.77409422e-04],
       [1.29872382e-01, 8.70121062e-01, 6.59382749e-06],
       [9.64054644e-01, 2.16718502e-02, 1.42735830e-02],
       [1.57211408e-01, 1.13099910e-01, 7.29688764e-01],
       [9.98306930e-01, 7.62273034e-04, 9.30878043e-04],
       [2.41171807e-01, 7.58071780e-01, 7.56474561e-04],
       [1.58256635e-01, 1.12181783e-01, 7.29561508e-01],
       [9.78794992e-01, 1.72797889e-02, 3.92520661e-03],
       [9.93173599e-01, 6.36102818e-03, 4.65443329e-04],
       [1.65036425e-01, 1.06459960e-01, 7.28503585e-01],
       [2.54812390e-02, 9.74516094e-01, 2.72807415e-06],
       [2.20897812e-02, 9.77904618e-01, 5.66625249e-06],
       [1.53487667e-01, 1.16453119e-01, 7.30059206e-01],
       [9.75413501e-01, 7.35935289e-03, 1.72271132e-02],
       [9.52446401e-01, 3.03664878e-02, 1.71870403e-02],
       [1.54758766e-01, 1.15293749e-01, 7.29947448e-01],
       [9.97713089e-01, 1.36486342e-04, 2.15034327e-03],
       [1.51974097e-01, 1.17854021e-01, 7.30171740e-01],
       [4.47333977e-02, 9.55223024e-01, 4.35717666e-05],
       [1.71548188e-01, 1.01320222e-01, 7.27131546e-01],
       [1.64586738e-01, 1.06827408e-01, 7.28585839e-01],
       [1.60620153e-01, 1.10141970e-01, 7.29237914e-01],
       [1.67937160e-01, 1.04129262e-01, 7.27933586e-01],
       [9.92277622e-01, 6.72303047e-03, 9.99298878e-04],
       [9.96952295e-01, 5.02690273e-05, 2.99744424e-03],
       [1.60694569e-01, 1.10078543e-01, 7.29226947e-01],
       [7.77151361e-02, 9.22259212e-01, 2.56550920e-05],
       [9.54834461e-01, 2.20688321e-02, 2.30966732e-02],
       [2.45005209e-02, 9.75432098e-01, 6.73643008e-05],
       [1.65767431e-01, 1.05866201e-01, 7.28366375e-01],
       [9.56177473e-01, 3.94766219e-02, 4.34593949e-03],
       [9.93002951e-01, 7.53679080e-04, 6.24330854e-03]], dtype=float32)

In [13]:
penguins['species']

0         Adelie
1      Chinstrap
2         Gentoo
3      Chinstrap
4         Adelie
         ...
328       Adelie
329    Chinstrap
330       Gentoo
331       Adelie
332       Adelie
Name: species, Length: 333, dtype: str

In [14]:
penguins_y

array([0, 1, 2, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 1, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 2,
       0, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1, 2, 1, 2, 0, 1, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2,
       1, 1, 2, 0, 2, 1, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2,
       1, 2, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0,
       0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0,
       1, 0, 2, 0, 2, 2, 0, 0, 2, 0, 1, 2, 0, 1, 1, 2, 0, 0, 2, 1, 1, 0,
       0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0,
       1, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 1, 0, 2, 2,
       1, 2, 2, 2, 0, 1, 0, 1, 2, 2, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       2, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 0, 2, 0, 1, 2,
       0, 0, 2, 1, 1, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1,
       2, 0, 0], dtype=int8)